#!/bin/bash

intltool-extract --type=gettext/glade resources/menta-install.glade
intltool-extract --type=gettext/glade resources/package-tile.glade
xgettext --language=Python \
         -cTRANSLATORS \
         --keyword=_ \
         --keyword=N_ \
         --from-code=UTF-8 \
         --output=menta-install.pot \
         usr/lib/menta-install/*.py \
         usr/lib/menta-install/installer/*.py \
         resources/*.glade.h

rm -f resources/*.glade.h
