#!/bin/bash

# Runtime dependencies, as listed in debian/control
sudo apt install --no-install-recommends appstream apt-config-icons gir1.2-appstream-1.0 gir1.2-packagekitglib-1.0 \
    gir1.2-xmlb-2.0 packagekit python3-apt python3-gi-cairo python3-html2text \
    python3-requests python3-setproctitle

sudo rm -rf /usr/lib/menta-install
sudo cp -R usr /
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
sudo gtk-update-icon-cache /usr/share/icons/hicolor
cd resources && sudo glib-compile-resources \
    --target=/usr/share/menta-install/menta-install.gresource menta-install.gresource.xml \
    && cd ..

DEBUG=1 menta-install
