#!/bin/bash

sudo rm -rf /usr/lib/menta-install
sudo cp -R usr /
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
sudo gtk-update-icon-cache /usr/share/icons/hicolor
cd resources && sudo glib-compile-resources \
    --target=/usr/share/menta-install/menta-install.gresource menta-install.gresource.xml \
    && cd ..

DEBUG=1 menta-install
